import Navbar from '@/components/navbar/navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import ClientOnly from '@/components/ClientOnly'
import Modal from '@/components/modals/Modal'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'air-bnb',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientOnly>
          <Modal actionLabel='Submit' title = 'hello there' isOpen/>
          <Navbar/>
        </ClientOnly>
        {children}
        </body>
    </html>
  )
}
